### ISSUE TITLE
Question/Feature Request: Full configuration as code

### ISSUE THREAD

**Issue by gomesp** [jenkinsci/amazon-ecs-plugin#101]
Hi team

I noticed that your plugin does not currently support the [configuration-as-code plugin](https://github.com/jenkinsci/configuration-as-code-plugin/). 

Looking at your README.md and at your [ECSDeclarativeAgent.java class](https://github.com/jenkinsci/amazon-ecs-plugin/blob/e7909347c858dde31179cac9dff3062c699d5a94/src/main/java/com/cloudbees/jenkins/plugins/amazonecs/pipeline/ECSDeclarativeAgent.java#L288), I had the impression that this may not even be required, but I was hoping you could help me out. 

What I would like to achieve is to configure the build agents cloud 100% scripted. Currently the ```configuration-as-code``` plugin is my go-to approach, falling back to groovy on the exception.

Do you have any samples where you configure your build agents as code, instead of manually entering the configuration in the Jenkins web console? 

Thanks, I appreciate any help given!

**Comment by ChristopheBougere** [comment]
Did you find a way to achieve this @gomesp ?

**Comment by gomesp** [comment]
> Did you find a way to achieve this @gomesp ?

Not yet. But it seems that @markyjackson-taulia is picking it up, so this is great news. 

Currently I use the EC2 plugin to spin up agents dynamically (which supports CasC), but I'm looking forward to move to ECS with this plugin in the future.

**Comment by ChristopheBougere** [comment]
Good news is there anywhere we can track progress @markyjackson-taulia ?
I was planning to use Fargate, so I'd like to start directly using this plugin :/

**Comment by markyjackson-taulia** [comment]
I am still debugging

**Comment by pbsladek** [comment]
@gomesp I use this plugin everyday via jcasc. Happy to help out on any specific issues you are having. Here is one of the slave configs i use.

```yaml
  clouds:
    - ecs: # 4cpu-8gb
        cluster: "arn:aws:ecs:${AWS_REGION}:${AWS_ACCOUNT_ID}:cluster/xxxxxx-${AWS_JENKINS_ENVIRONMENT}-jenkins-ecs-cluster"
        credentialsId: "cmdt_jenkins_aws_credentials"
        jenkinsUrl: ${JENKINS_HOST_URL}
        name: amz2-4cpu-8gb
        regionName: ${AWS_REGION}
        retentionTimeout: 60
        tunnel: "${JENKINS_TUNNEL_URL}:${JENKINS_SLAVE_PORT}"
        templates:
          - assignPublicIp: false
            cpu: 4096
            image: xxxxx/xxxxxxxxxxx
            label: amz2-4cpu-8gb
            launchType: EC2
            memory: 8192
            memoryReservation: 4096
            networkMode: default
            privileged: false
            remoteFSRoot: /home/jenkins
            templateName: amz2-4cpu-8gb
```
